Add bookings
RoketV/share_it_project pull request #2
Opened 2023-01-22 13:23 UTC by RoketV

Убрал аннотации @Data Lombok над классами Entity. IDE на них ругалась, просила сделать вручную

2023-01-22 17:19 UTC, andrew-larkin requested changes
Привет! Очень хорошо, немного правок внести и будем готовы двигаться дальше.

2023-01-22 17:19 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +
@Repository

2023-01-22 17:19 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/comments/Comment.java
> +    public Long getId() {
можно аннотациями ломбока сгенерировать геттеры и сеттеры

2023-01-22 17:19 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/comments/CommentRepository.java
> +
@Repository

2023-01-22 17:19 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public Long getId() {
@Getter and @Setter над классом

2023-01-22 17:19 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
@Repository

2023-01-22 17:19 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/model/User.java
>      public User() {
тоже аннотациями сгенерировать

2023-01-22 17:19 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
@Repository

2023-01-23 21:56 UTC, RoketV commented
всё вроде сделал. Не разобрался только
`    @NotBlank
    private String name;
    @Column(name = "email", unique = true)
    @Email
    @NotBlank
    private String email;

    public User() {`
не понял только как вот здесь unique = true заменить аннотациями. Вроде и так же часть аннотации

2023-02-12 19:20 UTC, merged